#ifndef VISUALIZATION_GLOBAL_H
#define VISUALIZATION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VISUALIZATION_LIBRARY)
#  define VISUALIZATIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define VISUALIZATIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // VISUALIZATION_GLOBAL_H
