#ifndef MOVEMENTAMOUNT_GLOBAL_H
#define MOVEMENTAMOUNT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MOVEMENTAMOUNT_LIBRARY)
#  define MOVEMENTAMOUNTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MOVEMENTAMOUNTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MOVEMENTAMOUNT_GLOBAL_H
